/*
 * Settings.h
 *
 *  Created on: Jan 12, 2016
 *      Author: natek
 */

#ifndef SRC_SETTINGS_H_
#define SRC_SETTINGS_H_

//shooter module
#define RAMPOTPOSITION 0.4076
#define RAMPOWER 0.60

//PID Controllers
//#define RSHOOTER_CONTROLLER_P -7.7
//#define RSHOOTER_CONTROLLER_I 0
//#define RSHOOTER_CONTROLLER_D -0.7

#define RSHOOTER_CONTROLLER_P -7.2
#define RSHOOTER_CONTROLLER_I 0
#define RSHOOTER_CONTROLLER_D 0
#define RBACK_COURT 0.27

#define AUTOSHOT 0.298
#define RINTAKESHOOTSIDE 0.55

#define PSHOOTER_CONTROLLER_P 0
#define PSHOOTER_CONTROLLER_I 0
#define PSHOOTER_CONTROLLER_D 0

//angles
#define RMAXIMUM_ANGLE .81
#define RMINIMUM_ANGLE .29

#define PMAXIMUM_ANGLE 0
#define PMINIMUM_ANGLE 0

#define RINTAKE_ANGLE 0.802551

#define LEVEL_ANGLE 0.7281
#define PINTAKE_ANGLE 0
#define RSHOOT_ANGLE 0.322551
//CAN values
#define SHOOTERMOTOR1 7
#define SHOOTERMOTOR2 8
#define ANGLEMOTOR 4

#define POT 0

#define DISTANCE_PER_PULSE .04477


//drive
#define DRIVE_CONTROLLER_P 0.012
#define DRIVE_CONTROLLER_I 0
#define DRIVE_CONTROLLER_D 0

#define ANGLE_CONTROLLER_P 0.04
#define ANGLE_CONTROLLER_I 0
#define ANGLE_CONTROLLER_D 0

#define DRIVE_LEFT1 2
#define DRIVE_LEFT2 5
#define DRIVE_RIGHT1 1
#define DRIVE_RIGHT2 6

#define DRIVE_ENCODER_1_A 7
#define DRIVE_ENCODER_1_B 8
#define DRIVE_ENCODER_2_A 5
#define DRIVE_ENCODER_2_B 6
#define TICKS_PER_INCH 13.479

//intake

#define INTAKE_MOTOR 3

#define TOMOHAWKS 2
#define INTAKE_SOL 0
#define SHOOTER_SOL 1


#endif /* SRC_SETTINGS_H_ */
